In [43]:
import pandas as pd

# Load the dataset
movies = pd.read_csv('datasets/tmdb_5000_movies.csv')
credits = pd.read_csv('datasets/tmdb_5000_credits.csv')

# Merge datasets on title
movies = movies.merge(credits, on='title')
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [44]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [45]:
movies.dropna(inplace=True)

In [57]:
movies.info

<bound method DataFrame.info of       movie_id                                     title  \
0        19995                                    Avatar
1          285  Pirates of the Caribbean: At World's End
2       206647                                   Spectre
3        49026                     The Dark Knight Rises
4        49529                               John Carter
...        ...                                       ...
4804      9367                               El Mariachi
4805     72766                                 Newlyweds
4806    231617                 Signed, Sealed, Delivered
4807    126186                          Shanghai Calling
4808     25975                         My Date with Drew

                                               overview  \
0     [In, the, 22nd, century,, a, paraplegic, Marin...
1     [Captain, Barbossa,, long, believed, to, be, d...
2     [A, cryptic, message, from, Bond’s, past, send...
3     [Following, the, death, of, District, Attorney...
4     [John, Carter, is, a, war-weary,, former, mili...
...                                                 ...
4804  [El, Mariachi, just, wants, to, play, his, gui...
4805  [A, newlywed, couple's, honeymoon, is, upended...
4806  ["Signed,, Sealed,, Delivered", introduces, a,...
4807  [When, ambitious, New, York, attorney, Sam, is...
4808  [Ever, since, the, second, grade, when, he, fi...

                                            genres  \
0     [Action, Adventure, Fantasy, ScienceFiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4              [Action, Adventure, ScienceFiction]
...                                            ...
4804                     [Action, Crime, Thriller]
4805                             [Comedy, Romance]
4806             [Comedy, Drama, Romance, TVMovie]
4807                                            []
4808                                 [Documentary]

                                               keywords  \
0     [cultureclash, future, spacewar, spacecolony, ...
1     [ocean, drugabuse, exoticisland, eastindiatrad...
2     [spy, basedonnovel, secretagent, sequel, mi6, ...
3     [dccomics, crimefighter, terrorist, secretiden...
4     [basedonnovel, mars, medallion, spacetravel, p...
...                                                 ...
4804  [unitedstates–mexicobarrier, legs, arms, paper...
4805                                                 []
4806  [date, loveatfirstsight, narration, investigat...
4807                                                 []
4808           [obsession, camcorder, crush, dreamgirl]

                                                cast                crew  \
0      [SamWorthington, ZoeSaldana, SigourneyWeaver]      [JamesCameron]
1         [JohnnyDepp, OrlandoBloom, KeiraKnightley]     [GoreVerbinski]
2          [DanielCraig, ChristophWaltz, LéaSeydoux]         [SamMendes]
3          [ChristianBale, MichaelCaine, GaryOldman]  [ChristopherNolan]
4        [TaylorKitsch, LynnCollins, SamanthaMorton]     [AndrewStanton]
...                                              ...                 ...
4804  [CarlosGallardo, JaimedeHoyos, PeterMarquardt]   [RobertRodriguez]
4805       [EdwardBurns, KerryBishé, MarshaDietlein]       [EdwardBurns]
4806         [EricMabius, KristinBooth, CrystalLowe]        [ScottSmith]
4807          [DanielHenney, ElizaCoupe, BillPaxton]        [DanielHsia]
4808  [DrewBarrymore, BrianHerzlinger, CoreyFeldman]   [BrianHerzlinger]

                                                   tags
0     [In, the, 22nd, century,, a, paraplegic, Marin...
1     [Captain, Barbossa,, long, believed, to, be, d...
2     [A, cryptic, message, from, Bond’s, past, send...
3     [Following, the, death, of, District, Attorney...
4     [John, Carter, is, a, war-weary,, former, mili...
...                                                 ...
4804  [El, Mariachi, just, wants, to, play, his, gui...
4805  [A, newlywed, couple's, honeymoon, is, upended...
4806  ["Signed,, Sealed,, Delivered", introduces, a,...
4807  [When, ambitious, New, York, attorney, Sam, is...
4808  [Ever, since, the, second, grade, when, he, fi...

[4806 rows x 8 columns]>

In [46]:
import ast

def convert(obj):
    return [i['name'] for i in ast.literal_eval(obj)]

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [47]:
def extract_cast(obj):
    return [i['name'] for i in ast.literal_eval(obj)[:3]]

movies['cast'] = movies['cast'].apply(extract_cast)

In [48]:
def get_director(obj):
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            return [i['name']]
    return []

movies['crew'] = movies['crew'].apply(get_director)

In [49]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [50]:
# Remove spaces in names (e.g., Sam Worthington -> SamWorthington)
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [51]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [52]:
new_df = movies[['movie_id', 'title', 'tags']]
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())
new_df.head()

/tmp/ipykernel_6544/105065634.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
/tmp/ipykernel_6544/105065634.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()
similarity = cosine_similarity(vectors)

In [54]:
import requests

API_KEY = 'c592172537b957fe9a13742d14a6188d'

def fetch_poster(movie_id):
    url = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US'
    data = requests.get(url).json()
    poster_path = data.get('poster_path')
    return f"https://image.tmdb.org/t/p/w500/{poster_path}" if poster_path else None, data.get('homepage') or f"https://www.themoviedb.org/movie/{movie_id}"

def recommend(movie):
    movie = movie.lower()
    if movie not in movies['title'].str.lower().values:
        return ["Movie not found."], [None], [None]  # Always return 3 values

    index = movies[movies['title'].str.lower() == movie].index[0]
    distances = list(enumerate(similarity[index]))
    movies_list = sorted(distances, reverse=True, key=lambda x: x[1])[1:9]

    recommended_titles = []
    recommended_posters = []
    recommended_links = []

    for i in movies_list:
        movie_id = movies.iloc[i[0]].movie_id
        title = movies.iloc[i[0]].title
        poster, link = fetch_poster(movie_id)
        recommended_titles.append(title)
        recommended_posters.append(poster)
        recommended_links.append(link)

    return recommended_titles, recommended_posters, recommended_links

In [55]:
recommend('Avatar')
recommend('The Dark Knight')
recommend('Pirates of the Caribbean: At World\'s End')

(["Pirates of the Caribbean: Dead Man's Chest",
  'Pirates of the Caribbean: On Stranger Tides',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  '20,000 Leagues Under the Sea',
  'Puss in Boots',
  'Life of Pi',
  'Waterworld',
  'The Pirates! In an Adventure with Scientists!'],
 ['https://image.tmdb.org/t/p/w500//lAhcKRt0ggTFkeFL95jrGQYaRXs.jpg',
  'https://image.tmdb.org/t/p/w500//keGfSvCmYj7CvdRx36OdVrAEibE.jpg',
  'https://image.tmdb.org/t/p/w500//z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg',
  'https://image.tmdb.org/t/p/w500//heAEH85fdxEgV98LizHbQCL95iZ.jpg',
  'https://image.tmdb.org/t/p/w500//eufJ36oQCauDc427ewaEvQrhZ6i.jpg',
  'https://image.tmdb.org/t/p/w500//iLgRu4hhSr6V1uManX6ukDriiSc.jpg',
  'https://image.tmdb.org/t/p/w500//pBjf3xzi6kClzWXiKMclMUX7dOP.jpg',
  'https://image.tmdb.org/t/p/w500//bkLeXPDP6sramrTiF5W7TzUl4t0.jpg'],
 ['https://movies.disney.com/pirates-of-the-caribbean-dead-mans-chest',
  'https://movies.disney.com/pirates-of-the-caribbean-on-stranger-tides',
  'https://movies.disney.com/pirates-of-the-caribbean-the-curse-of-the-black-pearl',
  'https://www.themoviedb.org/movie/173',
  'https://www.dreamworks.com/movies/puss-in-boots',
  'https://www.20thcenturystudios.com/movies/life-of-pi',
  'https://www.themoviedb.org/movie/9804',
  'https://www.sonypictures.com/movies/thepiratesbandofmisfits'])

In [56]:
import pickle

pickle.dump(new_df, open('movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))